/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Nat64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Contact = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
export const CheckIn = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Nat64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'getAlertHistory' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getLocationHistory' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeContact' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendSOS' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Nat64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Contact = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const CheckIn = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Nat64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'getAlertHistory' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getLocationHistory' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeContact' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendSOS' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };